name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Ubuntu 20.04-64bit,                   os: ubuntu-20.04,   shell: bash, artifact: 'SDL-ubuntu20.04-64bit' }
        - { name: Ubuntu 20.04-32bit,                   os: ubuntu-20.04,   shell: bash, artifact: 'SDL-ubuntu20.04-32bit', cmake: '-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DSDL_IBUS=FALSE' }
        
    steps:

    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install build-essential git \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libusb-1.0-0-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev \
            gcc-multilib g++-multilib libwayland-dev:i386


    - uses: actions/checkout@v4
    - name: Check that versioning is consistent
      # We only need to run this once: arbitrarily use the Linux/CMake build
      if: "runner.os == 'Linux'"
      run: ./build-scripts/test-versioning.sh
    - name: Configure (CMake)
      run: |
        ${{ matrix.platform.source_cmd }}
        cmake -S . -B build -G Ninja \
          -Wdeprecated -Wdev -Werror \
          -DSDL_SHARED=ON \
          -DSDL_STATIC=ON \
          -DSDL_TESTS=ON \
          -DSDL_WERROR=ON \
          -DSDL_INSTALL_TESTS=ON \
          -DSDL_VENDOR_INFO="Github Workflow" \
          -DSDL_CLANG_TIDY=ON \
          -DCMAKE_INSTALL_PREFIX=cmake_prefix \
          -DCMAKE_BUILD_TYPE=Release \
          ${{ matrix.platform.cmake }}
    - name: Build (CMake)
      id: build
      run: |
        ${{ matrix.platform.source_cmd }}
        cmake --build build/ --config Release --verbose --parallel
    - name: Run build-time tests (CMake)
      run: |
        ${{ matrix.platform.source_cmd }}
        set -eu
        export SDL_TESTS_QUICK=1
        ctest -VV --test-dir build/ -j2
        if test "${{ runner.os }}" = "Linux"; then
          # This should show us the SDL_REVISION
          strings build/libSDL3.so.0 | grep SDL-
        fi
    - name: Install (CMake)
      run: |
        ${{ matrix.platform.source_cmd }}
        set -eu
        cmake --install build/ --config Release
        ( cd cmake_prefix; find . ) | LC_ALL=C sort -u
    - name: Package (CPack)
      if: ${{ always() && steps.build.outcome == 'success' }}
      run: |
        cmake --build build/ --config Release --target package
    - uses: actions/upload-artifact@v4
      if: ${{ always() && steps.build.outcome == 'success' }}
      with:
        if-no-files-found: error
        name: ${{ matrix.platform.artifact }}
        path: build/dist/SDL3*
